// <auto-generated />
using System;
using BatalhaDePokemons.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BatalhaDePokemons.Infra.Migrations
{
    [DbContext(typeof(PokemonsDbContext))]
    [Migration("20250331130447_AdicionaMappingParaPokemon")]
    partial class AdicionaMappingParaPokemon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Pokemon", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PokemonId");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipo");

                    b.HasKey("PokemonId");

                    b.ToTable("Pokemons", (string)null);
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Pokemon", b =>
                {
                    b.OwnsOne("BatalhaDePokemons.Domain.Models.StatusDeCombate", "Status", b1 =>
                        {
                            b1.Property<Guid>("PokemonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Atk")
                                .HasColumnType("int")
                                .HasColumnName("Atk");

                            b1.Property<int>("Def")
                                .HasColumnType("int")
                                .HasColumnName("Def");

                            b1.Property<int>("HP")
                                .HasColumnType("int")
                                .HasColumnName("Hp");

                            b1.Property<int>("Spd")
                                .HasColumnType("int")
                                .HasColumnName("Spd");

                            b1.HasKey("PokemonId");

                            b1.ToTable("Pokemons");

                            b1.WithOwner()
                                .HasForeignKey("PokemonId");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
