// <auto-generated />
using System;
using BatalhaDePokemons.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BatalhaDePokemons.Infra.Migrations
{
    [DbContext(typeof(PokemonsDbContext))]
    partial class PokemonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Ataque", b =>
                {
                    b.Property<Guid>("AtaqueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AtaqueId");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataHoraCriacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Poder")
                        .HasColumnType("int")
                        .HasColumnName("Poder");

                    b.Property<int>("Precisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50)
                        .HasColumnName("Precisao");

                    b.Property<int>("QuantUsos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipo");

                    b.HasKey("AtaqueId");

                    b.ToTable("Ataques", (string)null);
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Batalha", b =>
                {
                    b.Property<Guid>("BatalhaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BatalhaId");

                    b.Property<bool>("IsFinalizada")
                        .HasColumnType("bit")
                        .HasColumnName("IsFinalizada");

                    b.Property<Guid>("Pokemon1Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Pokemon1Id");

                    b.Property<Guid>("Pokemon2Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Pokemon2Id");

                    b.Property<Guid>("ProximoTurnoDoPokemonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProximoTurnoDoPokemonId");

                    b.Property<Guid?>("VencedorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("VencedorId");

                    b.HasKey("BatalhaId");

                    b.ToTable("Batalhas", (string)null);
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Pokemon", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PokemonId");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataHoraCriacao");

                    b.Property<bool>("IsDesmaiado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDesmaiado");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Level");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipo");

                    b.HasKey("PokemonId");

                    b.ToTable("Pokemons", (string)null);
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.PokemonAtaque", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PokemonId");

                    b.Property<Guid>("AtaqueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AtaqueId");

                    b.HasKey("PokemonId", "AtaqueId");

                    b.HasIndex("AtaqueId");

                    b.ToTable("PokemonAtaque", (string)null);
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Turno", b =>
                {
                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TurnoId");

                    b.Property<Guid>("AlvoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AlvoId");

                    b.Property<Guid>("AtacanteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AtacanteId");

                    b.Property<Guid>("AtaqueUtilizadoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AtaqueUtilizadoId");

                    b.Property<Guid>("BatalhaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BatalhaId");

                    b.Property<int>("DanoCausado")
                        .HasColumnType("int")
                        .HasColumnName("DanoCausado");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataHoraCriacao");

                    b.Property<int>("NumeroTurno")
                        .HasColumnType("int")
                        .HasColumnName("NumeroTurno");

                    b.HasKey("TurnoId");

                    b.HasIndex("BatalhaId");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Pokemon", b =>
                {
                    b.OwnsOne("BatalhaDePokemons.Domain.Models.StatusDeCombate", "Status", b1 =>
                        {
                            b1.Property<Guid>("PokemonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Atk")
                                .HasColumnType("int")
                                .HasColumnName("Atk");

                            b1.Property<int>("Def")
                                .HasColumnType("int")
                                .HasColumnName("Def");

                            b1.Property<int>("Hp")
                                .HasColumnType("int")
                                .HasColumnName("Hp");

                            b1.Property<int>("Spd")
                                .HasColumnType("int")
                                .HasColumnName("Spd");

                            b1.HasKey("PokemonId");

                            b1.ToTable("Pokemons");

                            b1.WithOwner()
                                .HasForeignKey("PokemonId");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.PokemonAtaque", b =>
                {
                    b.HasOne("BatalhaDePokemons.Domain.Models.Ataque", "Ataque")
                        .WithMany("PokemonAtaques")
                        .HasForeignKey("AtaqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatalhaDePokemons.Domain.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonAtaques")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ataque");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Turno", b =>
                {
                    b.HasOne("BatalhaDePokemons.Domain.Models.Batalha", "Batalha")
                        .WithMany("Turnos")
                        .HasForeignKey("BatalhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batalha");
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Ataque", b =>
                {
                    b.Navigation("PokemonAtaques");
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Batalha", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("BatalhaDePokemons.Domain.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonAtaques");
                });
#pragma warning restore 612, 618
        }
    }
}
